### ISSUE TITLE
Fix Search Editor bugs

### ISSUE THREAD

**Issue by flourish86** [Icinga/ipl-web#32]
## Clicking suggestions from the dropdown won't work (in Safari)

When clicking a suggestion from the dropdown the dropdown will be closed, but the value won't be applied. It neither works for columns, operator nor value suggestions. Selecting a value by keyboard works, though.

![Screen Recording 2021-08-30 at 15 09 41](https://user-images.githubusercontent.com/6977434/131344252-701d766f-07d0-42b0-a88a-b1c079207f6d.gif)

## Parsing Error when copying and pasting urls
When copying and pasting Urls with filter syntax that contain `>=` or `<=` they are parsed wrong.
* e.g. http://10.211.55.10/icingaweb2/icingadb/hosts?host.name%3E%3Dtest

**Copied url**
![Screen Shot 2021-08-30 at 14 58 59](https://user-images.githubusercontent.com/6977434/131343027-ee2e8589-a615-4014-b0b5-b6b5b2399e83.png)

**results in**
![Screen Shot 2021-08-30 at 14 59 03](https://user-images.githubusercontent.com/6977434/131342926-050a8608-41c6-401a-8d52-cc787db6eec5.png)

Browsers: Chrome, Safari, Firefox

## Suggestion flyout exceeding viewport.
![Screen Recording 2021-08-30 at 15 16 45](https://user-images.githubusercontent.com/6977434/131345205-71d124d7-92ad-4935-91e9-0eddd3c873d3.gif)

## Keyboard Shortcuts should work with Cmd instead of Ctrl on Mac
* Keyboard shortcuts, like `Ctrl + A` for selecting all should work with `Cmd + A`
* Copying and pasting shortcuts have no effect (at least on Mac, neither `Ctrl` nor `Cmd` will work)

## Can't deselect, after using `Ctrl + A` for selecting all
* After selecting the filter with `Ctrl + A` the filter "pills" get highlighted, but they can't be deselected.

**Comment by nilmerg** [comment]
> When copying and pasting Urls with filter syntax that contain >= or <= they are parsed wrong.

Are you copying from the address bar? This isn't supported, only from the searchbar and to the searchbar this is supported. Otherwise you have to ensure yourself that the copied string isn't escaped.

> Copying and pasting shortcuts have no effect (at least on Mac, neither Ctrl nor Cmd will work)

We use events for this, not keystrokes. And regarding [caniuse](https://caniuse.com/clipboard) this should work on all major browsers.

> Can't deselect, after using Ctrl + A for selecting all

The searchbar follows the usual text selection principles here. To deselect the cursor has to move. Either by clicking somewhere with the mouse, by using the arrow keys or the keys Pos1 and End.
